main: kr.nuyar.www.closeui.CloseUI
name: ${project.artifactId}
version: '${project.version}'
description: cancel mod ui
author: nuYaR
website: www.nuyar.kr

commands:
  closeui:
    description: CloseUI command